run:
  timeout: 5m
linters:
  enable-all: true
  disable:
    - cyclop
    - wsl
    - godox
    - gochecknoglobals
    - ireturn
    - nlreturn
    - testpackage
    - paralleltest
    - exhaustivestruct
    - exhaustruct
    - gocognit
    - gochecknoinits
    - gocyclo
    - maligned
    - funlen
    - maintidx
    - musttag
    - nosnakecase
