name: Build and release GatewayD

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go 1.20
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
          cache: true
      - name: Install nfpm for building Linux packages
        run: go install github.com/goreleaser/nfpm/v2/cmd/nfpm@latest
      - name: Build and release binaries
        run: make build-release
      - name: Build and release Linux packages
        run: make build-linux-packages
      - name: Sign in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Sign in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            gatewaydio/gatewayd:${{ github.ref_name }}
            gatewaydio/gatewayd:latest
            ghcr.io/gatewayd-io/gatewayd:${{ github.ref_name }}
            ghcr.io/gatewayd-io/gatewayd:latest
          platforms: linux/amd64
      - name: Scan Docker image with Syft and generate SBOM
        uses: anchore/sbom-action@v0
        with:
          artifact-name: gatewayd-image-${{ github.ref_name }}.cyclonedx.json
          format: cyclonedx-json
          dependency-snapshot: true
          image: gatewaydio/gatewayd:${{ github.ref_name }}
      - name: Scan source code and generate SBOM
        run: |
          go install github.com/CycloneDX/cyclonedx-gomod/cmd/cyclonedx-gomod@latest
          cyclonedx-gomod mod -json -licenses -output gatewayd-source-${{ github.ref_name }}.cyclonedx.json
      - name: Create release and add artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.tar.gz
            dist/checksums.txt
            dist/*.deb
            dist/*.rpm
            dist/*.zip
            gatewayd-image-${{ github.ref_name }}.cyclonedx.json
            gatewayd-source-${{ github.ref_name }}.cyclonedx.json
          draft: false
          prerelease: false
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          generate_release_notes: true
